version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: ZIC_DB_pg
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: alex
      POSTGRES_DB: ZIC-SERVER-main
    ports:
      - "5444:5432"
    networks:
      - zic_network
    volumes:
      - pg_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ZIC_Server
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: alex
      DB_PASSWORD: alex
      DB_SSLMODE: disable
      DB_NAME: ZIC-SERVER-main
    ports:
      - "8385:8385" 
    networks:
      - zic_network

networks:
  zic_network:
    driver: bridge


volumes:
  pg_data: