version: '3.8'

services:
  # Сервис базы данных PostgreSQL
  db:
    image: postgres:latest
    container_name: ZIC_DB_pg
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: alex
      POSTGRES_DB: ZIC-SERVER-main
    volumes:
      - db_data:/var/lib/postgresql/data  # Персистентное хранилище данных
    restart: always  # Автоматический перезапуск контейнера
    networks:
      - vpn-network  # Сеть для подключения через VPN (без проброса портов наружу)

  # Сервис сервера
  server:
    image: antalkon/zic_c_server:2.1  # Ваш образ сервера
    container_name: ZIC_SERVER
    depends_on:
      - db  # Гарантирует, что база данных запустится перед сервером
    restart: always  # Автоматический перезапуск контейнера
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: alex
      DB_PASSWORD: alex
      DB_SSLMODE: disable
      DB_NAME: ZIC-SERVER-main

    networks:
      - vpn-network  # Сеть для подключения через VPN (без проброса портов наружу)
    command: ["./server"]  # Запуск вашего Go-сервера

# Для хранения данных базы данных
volumes:
  db_data:

# Сетевые настройки
networks:
  vpn-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.0.0/24  # VPN-сеть