name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22' # Укажите нужную версию Go

      - name: Build
        run: go build -o myapp ./cmd/myapp # Соберите ваше приложение

      - name: Build Docker Image
        run: |
          docker build -t myapp:latest . # Соберите Docker-образ из Dockerfile

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} # Имя пользователя Docker Hub
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} # Пароль Docker Hub
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag myapp:latest $DOCKER_USERNAME/myapp:latest # Тегируйте образ
          docker push $DOCKER_USERNAME/myapp:latest # Загружайте образ на Docker Hub
